---
name: Apptainer Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: ['**']

jobs:
    apptainer-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Apptainer
              uses: eWaterCycle/setup-apptainer@v2
              with:
                  apptainer-version: 1.3.6

            - name: Run an apptainer container
              run: apptainer run docker://alpine cat /etc/os-release
